#name: annotation_route
#description: auto generate router config
#version: 0.0.2
#author: voicewitness<voicewitness@gmail.com>
#homepage: https://github.com/alibaba-flutter/annotation_route
#dependencies:
#  analyzer: any
#  build: any
#  source_gen: '>=0.8.0'
#  build_config: '>=0.3.0'
#  mustache4dart: any
#dev_dependencies:
#  build_runner: '>=0.9.1'
#  test: any
#
#environment:
#  sdk: '>=2.0.0 <3.0.0'

name: flutter_route
description: A new Flutter package project.
version: 0.0.1
dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_boost:  ^1.12.13
  build_runner: '>=0.9.1'
  source_gen: '>=0.8.0'
#  mustache4dart: '>=3.0.0-dev.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"